[server]
server_port = ":5000"
origins = ["http://localhost:3000", "https://example.com"]

[database]
db_host = "localhost"
db_port = "5432"
db_user = "postgres"
db_password = "sahil"
db_name = "graphql"

[jwt]
signing_key = "K3#v@9$1!pZ^mL2&uQ7*rF4)gT8_W+oB"
encryption_key = "8x@R!5#N0$kQ7_vT3&Wp2+Z^fC6*bM1h"
